version: '3.8'

services:
  app:
    image: yusufokr0/school-management-2:latest
    container_name: school-management-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/school_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    networks:
      - school-net

  db:
    image: postgres:15-alpine
    container_name: school-management-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d school_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - school-net

volumes:
  postgres_data:

networks:
  school-net:
    driver: bridge
